[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
  { access = "read", path = "./script/config" },
  { access = "read", path = "./out" }
]

# Compiler settings.
solc = "0.8.30"
evm_version = "prague"
via_ir = true
optimizer = true
optimizer_runs = 200

# Test settings.
dynamic_test_linking = true

# Upgrades support.
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[profile.default.fmt]
single_line_statement_blocks = "single"
sort_imports = true
override_spacing = true
wrap_comments = true

[profile.lint]
exclude_lints = ["screaming-snake-case-immutable"]

[fuzz]
runs = 512

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
