[mainnet]
endpoint_url = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_API_KEY}"

[mainnet.address]
# https://app.morpho.org/ethereum/vault/0xBEeFFF209270748ddd194831b3fa287a5386f5bC/smokehouse-usdc
wrapped_vault = "0xBEeFFF209270748ddd194831b3fa287a5386f5bC"
keeper = "${MAINNET_KEEPER}"
manager = "${MAINNET_MANAGER}"
guardian = "${MAINNET_GUARDIAN}"
owner = "${MAINNET_OWNER}"
premium_collector = "${MAINNET_PREMIUM_COLLECTOR}"

[mainnet.uint]
premium_rate_bps = 100 # 1%
max_premium_rate_bps = 500 # 5%
minimum_request_assets = 1_000_000 # 1 USDC
